[General]
bld="D9F5Y9m56iJIxk5V5MFQ9w==|w8ZjTXvc3dwQYNItEWylAZK5BTlHqG5umdheWCGwtr/TlkiOK7D1KQTTE7YQ"

[Preferences]
screenIndex=0
windowHeight=1028
windowVisibility=2
windowWidth=945
windowX=966
windowY=43

[Vacancy]
bannerShownCount=1
